[buildPlans.kiosevka]
    family = "Kiosevka"
    design = [
        "calt-colons",
        "v-underscore-low",
    ]

    [buildPlans.kiosevka.weights.thin]
    shape = 100
    menu  = 100
    css   = 100

    [buildPlans.kiosevka.weights.extralight]
    shape = 200
    menu  = 200
    css   = 200

    [buildPlans.kiosevka.weights.light]
    shape = 300
    menu  = 300
    css   = 300

    [buildPlans.kiosevka.weights.regular]
    shape = 400
    menu  = 400
    css   = 400

    [buildPlans.kiosevka.weights.medium]
    shape = 500
    menu  = 500
    css   = 500

    [buildPlans.kiosevka.weights.semibold]
    shape = 600
    menu  = 600
    css   = 600

    [buildPlans.kiosevka.weights.bold]
    shape = 700
    menu  = 700
    css   = 700

    [buildPlans.kiosevka.weights.extrabold]
    shape = 800
    menu  = 800
    css   = 800

    [buildPlans.kiosevka.weights.heavy]
    shape = 900
    menu  = 900
    css   = 900
